# Generated by Django 4.0.4 on 2022-05-18 05:17

from django.db import migrations, models
import wfscript.materials.mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            bases=(models.Model, wfscript.materials.mixin.WorkflowMaterial),
        ),
    ]
