# Generated by Django 4.0.4 on 2022-05-17 03:31

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=36, unique=True)),
                ('method', models.CharField(max_length=100)),
                ('state', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('resume_method', models.CharField(max_length=100)),
                ('resume_step', models.CharField(max_length=50)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('payload', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='response', to='wfscript_api.payload')),
            ],
        ),
        migrations.AddField(
            model_name='payload',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payloads', to='wfscript_api.run'),
        ),
    ]
